language: c

dist: trusty
sudo: required

addons:
        apt:
                update: true
                sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-3.8
                packages:
                        - linux-headers-$(uname -r)
                        - gcc
                        - linux-libc-dev
                        - libpopt-dev
                        - libssl-dev
                        - libnuma-dev
                        - curl
                        - sshpass

         ssh_known_hosts:
                        - 47.95.5.155
compiler:
        - gcc



script:
       - chmod +x test
       - ./test
      


